services:
  - type: web
    name: ykrishi-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    branch: main
    runtime: python
    pythonVersion: 3.11